# -*- coding: utf-8 -*-
"""Another copy of SEM 2 ASSIGNMENT VARIABLE LIST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ePX3X8YOR21o4rBZl4LNk2ezV4_e1s9q

# Program Scenario: Cookies and Cakes Sales Management System

#### Description of the Program Requirements

The Taste A Bites Bakery's Cookies and Cakes Sales Management System is designed to help a bakery manage its stock, pricing, and sales of various cookies and cakes. The system allows for efficient management of multiple types of cookies and cakes, with features to handle customer orders, apply various discounts, and generate sales reports. Additionally, it supports special discounts for regular members and extra birthday discounts for members on their birthday.

1. **Manage Products:**
   - Add, update, and remove different types of cookies and cakes.
   - Set prices per piece.
   - Track stock levels for each product.

2. **Handle Orders:**
   - Allow customers to place orders for cookies and cakes.
   - Support pricing based on per-piece orders.
   - Apply discounts for member orders and birthday promotions.

3. **Customer Management:**
   - Maintain customer profiles, including membership status and birthday.
   - Apply regular member discounts.
   - Apply additional birthday discounts on the customer's birthday.

#### The Problem Your Program is Trying to Solve Using Object-Oriented Programming

The primary problem the program aims to solve is the efficient management of a bakery's sales operations. The program addresses the following issues:

1. **Inventory Management:** Keeping track of multiple product types, their stock levels, and pricing, which is essential for ensuring that the bakery can meet customer demand without overstocking or understocking.
2. **Order Processing:** Handling both small and large orders efficiently, calculating totals accurately, and applying any relevant discounts automatically.
3. **Customer Management:** Maintaining customer information and order history to enhance customer service and enable personalized marketing.

By using object-oriented programming (OOP), the program can be modular, scalable, and easy to maintain. OOP principles like encapsulation, inheritance, and polymorphism help manage the complexity of the system by organizing the code into manageable, reusable components.

#### Analysis of the Problem

To address the problems outlined, the system will be designed with the following classes and their interactions:

**1. Member Class:**
   - Attributes:  
 -id(int): The unique identifier for a member.             
 -name(string): The name of the member.                                          
 -birthdayDate (string): The birth date of the member, stored as a string(likely in a specific format such as "YYYY-MM-DD").                                
 -isMember (bool): A boolean indicating if the person is a member.              
 -isBirthday (bool): A boolean indicating if today is the member's birthday.
   
- Method:
   - Constructor                                                          
 -Member(): Default constructor, which does not initialize any attributes.                                
 -Member(bool, bool): Parameterized constructor that initializes the isMember and isBirthday attributes.

   - Setter  
 -void setIsBirthday(bool b): Sets the isBirthday attribute.                                
 -void setIsMember(bool m): Sets the isMember attribute.             
 -void setId(int p): Sets the id attribute.             
 -void setName(string n): Sets the name attribute             
 -void setPhoneNum(int p): Sets the phoneNum attribute.             
 -void setBirthdayDate(string b): Sets the birthdayDate -attribute.

   - Getter                                                                     
 -bool getIsBirthday() const: Returns the value of the isBirthday attribute.    
 -bool getIsMember() const: Returns the value of the isMember attribute.    
 -string getBirthdayDate() const: Returns the birthdayDate as a string.          

   - Other method         
 -bool checkMemberFile(string): Checks the member file (possibly for existence or validity) based on the given filename.    
 -bool verifyMember(int , string): Verifies the member's identity using their id and name.    
 -void addMember(const string &) const: Adds the member details to a file. The specific implementation details are not provided here.          

   - Destructor         
 -~Member(): Destructor for the Member class, which is called when an object of the class is destroyed. In this case, it is defined but does not perform any specific actions.


**2. StockItem Class:**
   - Attributes:  
-id (int): The unique identifier for the stock item.  
-name (string): The name of the stock item.  
-price (double): The price of the stock item.  
-quantity (int): The quantity of the stock item available in the inventory.       
   
- Method:
   - Constructor                                                          
 -StockItem(): Default constructor that initializes an empty StockItem object. It does not take any parameters.                                                                             
 -StockItem(int, const string&, double, int): Parameterized constructor that initializes a StockItem object with specific values for id, name, price, and quantity.

   - Getter                                                                     
 -int getId() const: Returns the id of the stock item.    
 -string getName() const: Returns the name of the stock item.          
 -double getPrice() const: Returns the price of the stock item.                
 -int getQuantity() const: Returns the quantity of the stock item.

   - Destructor                                   
 -~StockItem(): Destructor for the StockItem class. It is defined but does not perform any specific action. It ensures proper cleanup of resources when a StockItem object is destroyed.

**3. Stock Class:**
   - Attributes:  
-MAX_ITEMS (static const int): A constant defining the maximum number of stock items (cookies or cakes) that can be stored.  
-cookies (StockItem[MAX_ITEMS]): An array to store the stock items of type cookies.  
-cake (StockItem[MAX_ITEMS]): An array to store the stock items of type cakes.  
-numCookies (int): An integer to keep track of the number of cookie items currently in stock  
-numCakes (int): An integer to keep track of the number of cake items currently in stock.
   
- Method:
   - Constructor                                                          
 -Stock(): A default constructor that initializes a Stock object.                               

   - Stock Management Methods  
 -bool loadCookieStockData(string): Loads stock data for cookies from a file specified by fileName.  
 -bool loadCakeStockData(string): Loads stock data for cakes from a file specified by fileName.

   - Stock Finding Methods                                   
 -*StockItem findCookieId(int)**: Returns a pointer to the cookie item with the specified ID.    
 -*StockItem findCakeId(int)**: Returns a pointer to the cake item with the specified ID.          

   - Stock Updating Methods                                   
 -void updateCookieQuantity(const int&, int, string): Updates the quantity of the cookie item with the specified ID.    
 -void updateCakeQuantity(const int&, int, string): Updates the quantity of the cake item with the specified ID.         

   - Display                                   
 -void displayStockData(): Displays the current stock data, presumably by printing it to the console.

**4. Cart Class:**
   - Attributes:  
-MAX_ITEMS (static const int): A constant defining the maximum number of items (cookies or cakes) that can be stored in the cart.  
-cookieCartId (int[MAX_ITEMS]): An array to store the IDs of the cookie items in the cart.  
-cakeCartId (int[MAX_ITEMS]): An array to store the IDs of the cake items in the cart.  
-cookieCartQuantity (int[MAX_ITEMS]): An array to store the quantities of the cookie items in the cart.  
-cakeCartQuantity (int[MAX_ITEMS]): An array to store the quantities of the cake items in the cart.  
-numCookiesInCart (int): An integer to keep track of the number of cookie items currently in the cart..  
-numCakesInCart (int): An integer to keep track of the number of cake items currently in the cart.        
-stock (Stock*): A pointer to a Stock object, indicating composition; the cart has a relationship with the stock.
   
- Method:
   - Constructor                                                          
 -Cart(): A default constructor that initializes a Cart object without setting the stock.       
 -*Cart(Stock)**: A constructor that initializes a Cart object with a given Stock pointer.                               

   - Add to Cart Methods  
 -void addCookieToCart(int, int): Adds a specified quantity of a cookie item to the cart.
 -void addCakeToCart(int, int): Adds a specified quantity of a cake item to the cart.

   - Getter                                                                     
 -int getTotalCookieItems() const: Returns the total number of cookie items in the cart.    
 -int getTotalCakeItems() const: Returns the total number of cake items in the cart.    
 -int getCookieCartId(int) const: Returns the ID of the cookie item at the specified index in the cart.   
 -int getCookieCartQuantity(int) const: Returns the quantity of the cookie item at the specified index in the cart.   
 -int getCakeCartId(int) const: Returns the ID of the cake item at the specified index in the cart.   
 -int getCakeCartQuantity(int) const: Returns the quantity of the cake item at the specified index in the cart.   
 -Stock getStock() const*: Returns the Stock pointer associated with the cart.   

   - Friend Function                                   
 -friend ostream& operator<<(ostream& os, const Cart& cart): An overload of the << operator to allow easy printing of the cart's contents.    
   - Destructor                                   
 -~Cart(): A destructor to clean up when a Cart object is destroyed.

**5. Payment Class:**
   - Attributes:  
-cart (Cart*): A pointer to a Cart object, indicating composition. This means the Payment class is associated with a Cart object and can use it to calculate prices and manage stock.  
   
- Method:
   - Constructor                                                          
 -Payment(): A default constructor that initializes a Payment object without setting the cart.       
 -*Payment(Cart, bool, bool)**: A constructor that initializes a Payment object with a given Cart pointer and member status (isMember and isBirthday).                              

   - Calculation Methods  
 -double calculatePrice() const: Calculates the total price of the items in the cart.  
 -double calculateDiscount() const: Calculates the discount based on membership status and birthday status.  
 -double calculatePriceAfterDiscount() const: Calculates the price after applying the discount.  
 -double calculateTax() const: Calculates the tax on the price after discount.
 -double calculatePriceAfterTax() const: Calculates the final price after applying both discount and tax.  

   - Stock Management Method                                                                     
 -void updateStock(string, string): Updates the stock quantities based on the items in the cart.

   - Friend Function                                                                     
 -friend ostream& operator<<(ostream& os, const Payment& p): An overload of the << operator to allow easy printing of the payment details.

   - Destructor                                                                     
 -~Payment(): A destructor to clean up when a Payment object is destroyed.

**6. Customer Class:**
   - Attributes:  
-Stock stock: An instance of the Stock class, representing the inventory of cookies and cakes available in the bakery.       
-Member member: An instance of the Member class, representing the customer's membership information.       
-Cart cart: An instance of the Cart class, representing the items the customer has added to their cart.       
-Payment payment: An instance of the Payment class, representing the payment details for the customer's purchase.  
   
- Method:
   - Constructor                                                          
 -Customer(): Initializes a Customer object, possibly setting up initial states or configurations.       
                              
   - Discount Checking Method  
 -void checkDiscount(bool isMember, bool isBirthday): Checks and applies discounts based on whether the customer is a member and if it is their birthday.

   - Member Details Method                                                                     
 -void getMemberDetails(int id, string name, string birthdayDate): Sets the member details such as ID, name, and birthday date.

   - Stock Management Methods Function                                                                     
 -bool loadCookieStockData(string fileName): Loads stock data for cookies from a file specified by fileName.  
 -bool loadCakeStockData(string fileName): Loads stock data for cakes from a file specified by fileName.       
                              
   - Member Verification Methods                                                                     
 -bool checkMemberFile(string fileName): Checks the member file to see if a member exists.  
 -bool verifyMember(int id, string name): Verifies if a member exists with the given id and name.       
                              
   - Getter                                                                     
 -string getBirthdayDate(): Gets the birthday date of the member.       
                              
   - Display Method                                                                     
 -void displayStockData(string cookieFile, string cakeFile): Displays the stock data for cookies and cakes using the specified files.       
                              
   - Cart Management Methods                                                                     
 -void addCakeToCart(int id, int quantity): Adds a specified quantity of a cake (by ID) to the cart.  
 -void addCookieToCart(int id, int quantity): Adds a specified quantity of a cookie (by ID) to the cart.  
 -void displayCartContents(): Displays the contents of the cart.       
                              
   - Payment Method  
 -void printPaymentDetails(): Prints the payment details, likely including the total cost, discounts applied, and final amount.       
                              
   - Destructor  
 -~Customer(): A destructor to clean up when a Customer object is destroyed.

## Program Specification

### Inputs:
#### 1. User Choices:
- Whether to add cookies to the cart (true/false).
- Whether to add cakes to the cart (true/false).
- Whether to proceed with payment (true/false).

#### 2. Item Details:
- ID of the cookie or cake to be added.
- Quantity of the item to be added.

#### 3. Member Status:
- Boolean indicating if the user is a member.
- Boolean indicating if it's the user's birthday.

### Outputs:
#### Inventory Details:
- List of available cookies and cakes with IDs, names, types, and prices.

#### Cart Contents:
- Items in the cookie cart.
- Items in the cake cart.

#### Payment Details:
- Total price before discount.
- Discount amount.
- Price after discount.
- Tax amount.
- Final price after tax.

### Processes:
1. **Display Inventory:** Show available cookies and cakes with their details.
2. **Add Items to Cart:** Allow users to add cookies and cakes to their cart by specifying IDs and quantities.
3. **Calculate Prices:**
   - Calculate the total price of items in the cart.
   - Apply discounts if the user is a member.
   - Calculate tax based on the price after discount.
   - Calculate the final price after applying tax.
4. **Update Inventory:** Update the inventory quantities based on items purchased.
5. **Generate Receipt:** Display the payment details including discounts and taxes.

### Constraints:
- Valid IDs and quantities must be provided when adding items to the cart.
- Boolean values must be provided for user choices and member status.
- Inventory quantities should be updated correctly after purchase.

### Assumptions:
- All item prices and inventory quantities are predefined and available, which is maximum 100 pieces for both cookie and cake per day.
- Users provide valid inputs as prompted.
- Discounts and taxes are applied correctly based on the provided logic.

# files
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile memberDetails.txt
# id         name    phone number  birthday
# 117482745  Olivia  117482745     2000-1-27
# 142648589  Emma    142648589     1989-5-29
# 173245953  Amelia  173245953     1999-8-31
# 108758867  Evelyn  108758867     1970-2-8
# 192175421  Ava     192175421     1987-05-18
# 112891127  Luna    112891127     2001-5-14
# 112325510  Oliver  112325510     1990-7-23
# 132126753  Mateo   132126753     1988-1-1
# 127533218  Liam    127533218     2000-5-15

# Commented out IPython magic to ensure Python compatibility.
# %%writefile cakeDetails.txt
# id       name         type     price(RM)    quantity
# 101   lemon_cake------slice     18.99        10
# 102   chocolate_cake--slice     16.99        10
# 103   mango_cake------slice     18.99        10
# 104   oreo_cake-------slice     16.99        10
# 105   orange_cake-----slice     18.99        10
# 201   lemon_cake------whole     60.99        10
# 202   chocolate_cake--whole     60.99        10
# 203   mango_cake------whole     70.99        10
# 204   oreo_cake-------whole     70.99        10
# 205   orange_cake-----whole     60.99        10
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile cookiesDetails.txt
# id       name         type     price(RM)    quantity
# 301 oatmeal_cookie-----piece       2.99      30
# 302 chocolate_cookie---piece       2.99      30
# 303 peanut_cookie------piece       2.99      30
# 304 walnut_cookie------piece       2.99      30
# 305 almond_cookie------piece       2.99      30
# 401 oatmeal_cookie-----one_pack   15.99      10
# 402 chocolate_cookie---one_pack   15.99      10
# 403 peanut_cookie------one_pack   15.99      10
# 404 walnut_cookie------one_pack   15.99      10
# 405 almond_cookie------one_pack   15.99      10

# Commented out IPython magic to ensure Python compatibility.
# %%writefile paymentDetails.txt
# id       payment(RM)

"""# member"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Member.h
# #ifndef MEMBER_H
# #define MEMBER_H
# 
# #include <string>
# using namespace std;
# 
# class Member{
#   private:
#     int id;
#     string name;
#     int phoneNum;
#     string birthdayDate;
#     bool isMember;
#     bool isBirthday;
# 
#   public:
#     Member(){};
#     Member(bool, bool);
# 
#     void setIsBirthday(bool);
#     void setIsMember(bool);
#     void setId(int);
#     void setName(string);
#     void setPhoneNum(int);
#     void setBirthdayDate(string);
# 
#     bool getIsBirthday() const;
#     bool getIsMember() const;
#     string getBirthdayDate() const;
#     int getId () const;
# 
#     bool checkMemberFile(string);
#     bool verifyMember(int, string);
# 
#     void addMember(const string&)const;
# 
#     ~Member(){}
# };
# 
# #endif

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Member.cpp
# #include <iostream>
# #include <fstream>
# #include <ctime>
# #include "Member.h"
# using namespace std;
# 
# Member::Member(bool memberStatus, bool birthdayStatus){
#   isMember = memberStatus;
#   isBirthday = birthdayStatus;
# }
# 
# void Member::setIsBirthday(bool memberStatus){
#   isBirthday = memberStatus;
# }
# 
# void Member::setIsMember(bool memberStatus) {
#   isMember = memberStatus;
# }
# 
# void Member::setId(int p){
#   id = p;
# }
# 
# void Member::setName(string n){
#   name = n;
# }
# 
# void Member::setPhoneNum(int p){
#   phoneNum = p;
# }
# 
# void Member::setBirthdayDate(string b){
#   birthdayDate = b;
# }
# 
# bool Member::getIsBirthday() const{
#   return isBirthday;
# }
# 
# bool Member::getIsMember()const{
#   return isMember;
# }
# 
# string Member::getBirthdayDate() const {
#   return birthdayDate;
# };
# 
# int Member::getId () const {
#   return id;
# }
# 
# bool Member::checkMemberFile(string memberFName) {
#   ifstream inputFile(memberFName);
#     if (inputFile.is_open()) {
#         int id, phoneNum;
#         string name, birthdayDate;
#         string line;
#         getline(inputFile,line);
#         while (inputFile >> id >> name >> phoneNum >> birthdayDate) {
#               // do nothing
#         }
#         inputFile.close();
#         return true;
#     } else {
#         cout << "Unable to open file: " << memberFName << endl;
#         return false;
#     }
# }
# 
# bool Member::verifyMember(int i, string memberFName) {
#     ifstream inputFile(memberFName);
#     if (inputFile.is_open()) {
#         int memberId, memberPhoneNum;
#         string memberName, memberBirthdayDate;
#         string line;
#         getline(inputFile, line); // Skip header line
#         while (inputFile >> memberId >> memberName >> memberPhoneNum >> memberBirthdayDate) {
#             if (memberId == i) {
#                 cout << "Your identity is verified successfully." << endl;
#                 isMember = true;
#                 birthdayDate = memberBirthdayDate;
#                 inputFile.close();
#                 return true;
#                 break;
#             }
#         }
#         // If we reach here, the member ID was not found
#         cout << "Member not found with ID: " << i << endl;
#         inputFile.close();
#         return false;
#     } else {
#         cout << "Unable to open file: " << memberFName << endl;
#         return false;
#     }
# }
# 
# void Member::addMember(const string& filename)const{
#   ofstream outputFile(filename, ios::app); // Open file in append mode
#   if (outputFile.is_open()) {
#       outputFile << id << " " << name << " " << phoneNum << " " << birthdayDate << endl;
#       outputFile.close();
#       cout << "Congratulations, you're officially a member now!" << endl;
#   }
#   else {
#       cout << "Oops! Registration failed." << endl;
#   }
# }
#

"""
# StockItem"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile StockItem.h
# #ifndef STOCKITEM_H
# #define STOCKITEM_H
# 
# #include <string>
# using namespace std;
# 
# class StockItem{
#   private:
#     int id;
#     string name;
#     double price;
#     int quantity;
# 
#   public:
#     StockItem(){}
#     StockItem(int, const string& , double, int);
# 
#     int getId()const;
#     string getName()const;
#     double getPrice()const;
#     int getQuantity()const;
# 
#     ~StockItem(){}
# };
# 
# #endif

# Commented out IPython magic to ensure Python compatibility.
# %%writefile StockItem.cpp
# #include "StockItem.h"
# #include <iostream>
# using namespace std;
# 
# StockItem::StockItem(int i,const string& n, double p, int q){
#   id = i;
#   name = n;
#   price = p;
#   quantity = q;
# }
# 
# int StockItem::getId()const{
#   return id;
# }
# 
# string StockItem::getName()const{
#   return name;
# }
# 
# double StockItem::getPrice()const{
#   return price;
# }
# 
# int StockItem::getQuantity()const{
#   return quantity;
#   }
#

"""# Stock"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Stock.h
# #include "StockItem.h"
# #ifndef STOCK_H
# #define STOCK_H
# 
# class Stock{
#   private:
#     static const int MAX_ITEMS = 100;
#     StockItem cookies[MAX_ITEMS];
#     StockItem cake[MAX_ITEMS];
#     int numCookies;
#     int numCakes;
# 
#   public:
#   Stock(){}
# 
#   bool loadCookieStockData(string);
#   bool loadCakeStockData(string);
# 
#   StockItem* findCookieId(int);
#   StockItem* findCakeId(int);
# 
#   void updateCookieQuantity(const int&, int, string);
#   void updateCakeQuantity(const int&, int, string);
# 
#   void displayStockData(string, string);
#   ~Stock(){}
# };
# 
# #endif

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Stock.cpp
# #include "Stock.h"
# #include <iomanip>
# #include <iostream>
# #include <fstream>
# #include <string>
# using namespace std;
# 
# bool Stock::loadCookieStockData(string cookieFName){
#     int id, quantity;
#     string name;
#     double price;
#     numCookies = 0;
# 
#   ifstream cookiesFile(cookieFName);
# 
#   if (cookiesFile.is_open()){
#    string line;
#    getline(cookiesFile, line);
# 
#    while (cookiesFile >> id >> name >> price >> quantity) {
#     cookies[numCookies] = StockItem(id, name, price, quantity);
#     numCookies++;
#     }
#     cookiesFile.close();
#   }
#   else {
#     cout << "Unable to open " << cookieFName << endl;
#     return false;
#   }
# 
#    return true;
# }
# 
# bool Stock::loadCakeStockData(string cakeFName){
#     int id, quantity;
#     string name;
#     double price;
#     numCakes = 0;
# 
#   ifstream cakeFile(cakeFName);
#   if (cakeFile.is_open()){
#     string line;
#     getline(cakeFile, line); // Skip header
# 
#     while (cakeFile >> id >> name >> price >> quantity) {
#      cake[numCakes] = StockItem(id, name, price, quantity);
#      numCakes++;
#     }
#     cakeFile.close();
#   }
#   else {
#     cout << "Unable to open " << cakeFName << endl;
#     return false;
#   }
#  return true;
# }
# 
# 
# 
# StockItem* Stock::findCookieId(int id){
#   for (int i = 0; i < numCookies; i++){
#     if (cookies[i].getId() == id){
#       return &cookies[i];
#     }
#   }
#   return nullptr;
# }
# 
# StockItem* Stock::findCakeId(int id){
#   for (int i = 0; i < numCakes; i++){
#     if (cake[i].getId() == id){
#       return &cake[i];
#     }
#   }
#   return nullptr;
# }
# 
# void Stock::updateCookieQuantity(const int& itemId, int newQuantity,string cookieFName) {
#     const int loopNeeded = numCookies; // Add a semicolon at the end
# 
#     // Open the file for writing
#     ofstream cookiesFile(cookieFName);
#     if (!cookiesFile.is_open()) {
#         cerr << "Error opening " << cookieFName << endl;
#         return;
#     }
# 
#     // Write header
#     cookiesFile << "id name price quantity" << endl;
# 
#     // Loop through cookies and update quantity
#     for (int i = 0; i < loopNeeded; i++) {
#         if (cookies[i].getId() == itemId) { // Correct the function call
#             cookiesFile << cookies[i].getId() << " "
#                         << cookies[i].getName() << " "
#                         << cookies[i].getPrice() << " "
#                         << newQuantity << endl; // Add endl to go to the next line
#         }
#         else {
#             cookiesFile << cookies[i].getId() << " "
#                         << cookies[i].getName() << " "
#                         << cookies[i].getPrice() << " "
#                         << cookies[i].getQuantity() << endl; // Add endl to go to the next line
#         }
#     }
# 
#     // Close the file
#     cookiesFile.close();
# }
# 
# void Stock::updateCakeQuantity(const int& itemId, int newQuantity, string cakeFName) {
#     const int loopNeeded = numCakes;
# 
#     // Open the file for writing
#     ofstream cakeFile(cakeFName);
#     if (!cakeFile.is_open()) {
#         cout << "Error opening " << cakeFName << endl;
#         return;
#     }
# 
#     // Write header
#     cakeFile << "id name price quantity" << endl;
# 
#     // Loop through cake and update quantity
#     for (int i = 0; i < loopNeeded; i++) {
#         if (cake[i].getId() == itemId) {
#             cakeFile << cake[i].getId() << " "
#                      << cake[i].getName() << " "
#                      << cake[i].getPrice() << " "
#                      << newQuantity << endl;
#         }
#         else {
#             cakeFile << cake[i].getId() << " "
#                      << cake[i].getName() << " "
#                      << cake[i].getPrice() << " "
#                      << cake[i].getQuantity() << endl;
#         }
#     }
# 
#     // Close the file
#     cakeFile.close();
# }
# 
# void Stock::displayStockData(string cookieFName, string cakeFName) {
#     int id;
#     string name;
#     double price;
#     int quantity;
#     cout << "Cookies Details:" << endl;
#     ifstream cookiesFile(cookieFName);
#     if (cookiesFile.is_open()) {
#         cookiesFile.clear();
#         cookiesFile.seekg(0,ios::beg);
#         string line;
#         getline(cookiesFile, line);
#         cout  << left << setw(5) << "id" << setw(35) << "name (type)"  << setw(5) << "price(RM)" << endl;
#         while (cookiesFile >> id >> name >> price >> quantity) {
#             cout << left << setw(5) << id << setw(35) << name << setw(5) << price << endl;
#         }
#         cookiesFile.close();
#     }
#     else {
#         cout << "Unable to open " << cookieFName << endl;
#     }
# 
#     cout << "\nCakes Details:" << endl;
#     ifstream cakeFile(cakeFName);
#     if (cakeFile.is_open()) {
#         cakeFile.clear();
#         cakeFile.seekg(0,ios::beg);
#         string line;
#         getline(cakeFile, line);
#         cout  << left << setw(5) << "id" << setw(35) << "name (type)"  << setw(5) << "price(RM)" << endl;
#         while (cakeFile >> id >> name >> price >> quantity) {
#             cout << left << setw(5) << id << setw(35) << name << setw(5) << price << endl;
#         }
#         cakeFile.close();
#     }
#     else {
#         cout << "Unable to open " << cakeFName << endl;
#     }
# }

"""# Cart"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Cart.h
# #ifndef CART_H
# #define CART_H
# 
# #include "Stock.h"
# 
# class Cart {
#   private:
#     static const int MAX_ITEMS = 100;
#     int cookieCartId[MAX_ITEMS];
#     int cakeCartId[MAX_ITEMS];
#     int cookieCartQuantity[MAX_ITEMS];
#     int cakeCartQuantity[MAX_ITEMS];
#     int numCookiesInCart;
#     int numCakesInCart;
#     Stock* stock; // Composition
# 
#   public:
#     Cart(){}
#     Cart(Stock*);
# 
#     void addCookieToCart(int, int);
#     void addCakeToCart(int, int);
# 
#     int getTotalCookieItems() const;
#     int getTotalCakeItems() const;
# 
#     int getCookieCartId(int) const;
#     int getCookieCartQuantity(int) const;
#     int getCakeCartId(int) const;
#     int getCakeCartQuantity(int) const;
# 
#     Stock* getStock() const;
# 
#     friend ostream& operator<<(ostream& os, const Cart& cart);
# 
#     ~Cart(){}
# };
# 
# #endif
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Cart.cpp
# #include "Cart.h"
# #include <iostream>
# using namespace std;
# 
# Cart::Cart(Stock* s) {
#   stock = s;
#   numCookiesInCart = 0;
#   numCakesInCart = 0;
# }
# 
# void Cart::addCookieToCart(int i, int q) {
#     StockItem* item = stock->findCookieId(i);
#     if (item != nullptr) {
#         int availableQuantity = item->getQuantity();
#         if (availableQuantity >= q) {
#             bool itemFound = false;
# 
#             // Check if the item already exists in the cart
#             for (int j = 0; j < numCookiesInCart; ++j) {
#                 if (cookieCartId[j] == i) {
#                     // Item found in cart, update quantity
#                     cookieCartQuantity[j] = q;
#                     itemFound = true;
#                     cout << "Updated quantity of existing item in cart." << endl;
#                     break; // Exit the loop after updating quantity
#                 }
#             }
# 
#             if (!itemFound) {
#                 // Item not found in cart, add it
#                 cookieCartId[numCookiesInCart] = i;
#                 cookieCartQuantity[numCookiesInCart] = q;
#                 numCookiesInCart++;
#                 cout << "Cookie added to cart." << endl;
#             }
#         }
#         else if (availableQuantity > 0) {
#             cout << "Insufficient quantity in stock." << endl;
#             cout << "Remaining quantity: " << availableQuantity << endl;
#         }
#         else {
#             cout << "Cookie is out of stock." << endl;
#         }
#     }
#     else {
#         cout << "Cookie not found." << endl;
#     }
# }
# void Cart::addCakeToCart(int id, int quantity) {
#     StockItem* item = stock->findCakeId(id);
#     if (item != nullptr) {
#         int availableQuantity = item->getQuantity();
#         if (availableQuantity >= quantity) {
#             bool itemFound = false;
# 
#             // Check if the item already exists in the cart
#             for (int j = 0; j < numCakesInCart; ++j) {
#                 if (cakeCartId[j] == id) {
#                     // Item found in cart, update quantity
#                     cakeCartQuantity[j] = quantity;
#                     itemFound = true;
#                     cout << "Updated quantity of existing cake in cart." << endl;
#                     break; // Exit the loop after updating quantity
#                 }
#             }
# 
#             if (!itemFound) {
#                 // Item not found in cart, add it
#                 cakeCartId[numCakesInCart] = id;
#                 cakeCartQuantity[numCakesInCart] = quantity;
#                 numCakesInCart++;
#                 cout << "Cake added to cart." << endl;
#             }
#         } else if (availableQuantity > 0) {
#             cout << "Insufficient quantity in stock." << endl;
#             cout << "Remaining quantity: " << availableQuantity << endl;
#         } else {
#             cout << "Cake is out of stock." << endl;
#         }
#     } else {
#         cout << "Cake not found." << endl;
#     }
# }
# 
# int Cart::getTotalCookieItems() const {
#     return numCookiesInCart;
# }
# 
# int Cart::getTotalCakeItems() const {
#     return numCakesInCart;
# }
# 
# int Cart::getCookieCartId(int index) const {
#     return cookieCartId[index];
# }
# 
# int Cart::getCookieCartQuantity(int index) const {
#     return cookieCartQuantity[index];
# }
# 
# int Cart::getCakeCartId(int index) const {
#     return cakeCartId[index];
# }
# 
# int Cart::getCakeCartQuantity(int index) const {
#     return cakeCartQuantity[index];
# }
# 
# Stock* Cart::getStock() const {
#     return stock;
# }
# 
# ostream& operator<<(ostream& os, const Cart& cart) {
#     os << "Cookie Cart contents:\n";
#     if (cart.getTotalCookieItems() == 0) {
#       os << "No cookie found in your cart!" << endl;
#     }
#     for (int i = 0; i < cart.getTotalCookieItems(); ++i) {
#         os << "Cookie ID: " << cart.getCookieCartId(i) << ", Quantity: " << cart.getCookieCartQuantity(i) << "\n";
#     }
# 
#     os << "Cake Cart Contents:\n";
#     if (cart.getTotalCakeItems() == 0) {
#       os << "No cake found in your cart!" << endl;
#     }
#     for (int i = 0; i < cart.getTotalCakeItems(); ++i) {
#         os << "Cake ID: " << cart.getCakeCartId(i) << ", Quantity: " << cart.getCakeCartQuantity(i) << "\n";
#     }
#     return os;
# }

"""# Payment"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Payment.h
# #ifndef PAYMENT_H
# #define PAYMENT_H
# 
# #include "Member.h"
# #include "Cart.h"
# 
# class Payment:public Member {
#   private:
#     Cart* cart; // Composition
#     double totalPayment;
# 
#   public:
#     Payment(){}
#     Payment(Cart*, bool, bool);
# 
#     double calculatePrice();
#     double calculateDiscount();
#     double calculatePriceAfterDiscount();
#     double calculateTax();
#     double calculatePriceAfterTax();
# 
#     double getPriceAfterTax() const;
# 
#     void updateStock(string, string );
# 
#     friend ostream& operator<<(ostream& os,Payment& p);
# 
#     ~Payment(){}
# };
# 
# #endif

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Payment.cpp
# #include "Payment.h"
# #include <iostream>
# using namespace std;
# 
# Payment::Payment(Cart* c, bool memberStatus, bool birthdayStatus) : Member(memberStatus, birthdayStatus) {
#   cart = c;
#   setIsMember(memberStatus);
#   setIsBirthday(birthdayStatus);
#   totalPayment = 0;
# }
# 
# double Payment::calculatePrice() {
#     double sumCookiePrice = 0;
#     double sumCakePrice = 0;
# 
#     for (int i = 0; i < cart->getTotalCookieItems(); ++i) {
#         int cookieId = cart->getCookieCartId(i);
#         int quantity = cart->getCookieCartQuantity(i);
#         StockItem* cookieItem = cart->getStock()->findCookieId(cookieId);
#         if (cookieItem != nullptr) {
#             sumCookiePrice += cookieItem->getPrice() * quantity;
#         }
#     }
# 
#     for (int i = 0; i < cart->getTotalCakeItems(); ++i) {
#         int cakeId = cart->getCakeCartId(i);
#         int quantity = cart->getCakeCartQuantity(i);
#         StockItem* cakeItem = cart->getStock()->findCakeId(cakeId);
#         if (cakeItem != nullptr) {
#             sumCakePrice += cakeItem->getPrice() * quantity;
#         }
#     }
# 
#     return sumCookiePrice + sumCakePrice;
# }
# 
# double Payment::calculateDiscount() {
#     if (getIsBirthday()) {
#         return calculatePrice() * 0.3; // 30% discount for birthday
#     } else {
#         return calculatePrice() * 0.1; // 10% discount for normal member
#     }
# }
# 
# double Payment::calculatePriceAfterDiscount() {
#     return calculatePrice() - calculateDiscount();
# }
# 
# double Payment::calculateTax() {
#   if (getIsBirthday()){
#     return calculatePriceAfterDiscount() * 0.06;
#   }
#   else{
#     return calculatePrice() * 0.06;
#   }
# }
# 
# double Payment::calculatePriceAfterTax() {
#     totalPayment = calculatePriceAfterDiscount() + calculateTax();
#     return totalPayment;
# }
# 
# double Payment::getPriceAfterTax() const {
#   return totalPayment;
# };
# 
# void Payment::updateStock(string cookieFName, string cakeFName ) {
#     for (int i = 0; i < cart->getTotalCookieItems(); i++) {
#         int cookieId = cart->getCookieCartId(i);
#         StockItem* cookieItem = cart->getStock()->findCookieId(cookieId);
#         if (cookieItem != nullptr) {
#             int newQuantity = cookieItem->getQuantity() - cart->getCookieCartQuantity(i);
#             cart->getStock()->updateCookieQuantity(cookieId, newQuantity, cookieFName);
#         }
#     }
# 
#     for (int i = 0; i < cart->getTotalCakeItems(); i++) {
#         int cakeId = cart->getCakeCartId(i);
#         StockItem* cakeItem = cart->getStock()->findCakeId(cakeId);
#         if (cakeItem != nullptr) {
#             int newQuantity = cakeItem->getQuantity() - cart->getCakeCartQuantity(i);
#             cart->getStock()->updateCakeQuantity(cakeId, newQuantity, cakeFName);
#         }
#     }
# }
# 
# ostream& operator<<(ostream& os, Payment& p) {
#     if (p.getIsMember()){
#       os << "Total Price Before Discount: " << p.calculatePrice() << endl;
#       os << "Discount: " << p.calculateDiscount() << endl;
#       os << "Price After Discount: " << p.calculatePriceAfterDiscount() << endl;
#     }
#     else{
#     os << "Total Price Before Tax: " << p.calculatePrice() << endl;
#     }
#     os << "Tax: " << p.calculateTax() << endl;
#     os << "Price After Tax: " << p.calculatePriceAfterTax() << endl;
#     return os;
# }

"""# Customer"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Customer.h
# #ifndef CUSTOMER_H
# #define CUSTOMER_H
# #include "Member.h"
# #include "Stock.h"
# #include "Cart.h"
# #include "Payment.h"
# 
# class Customer {
#   private:
#     Stock stock;
#     Member member;
#     Cart cart;
#     Payment payment;
# 
#   public:
#   Customer();
# 
#   void checkDiscount(bool, bool);
# 
#   void getMemberDetails(int, string, string, string);
# 
#   bool loadCookieStockData(string);
# 
#   bool loadCakeStockData(string);
# 
#   bool checkMemberFile(string);
# 
#   bool verifyMember(int, string);
# 
#   string getBirthdayDate();
# 
#   void displayStockData(string, string);
# 
#   void addCakeToCart(int, int);
# 
#   void addCookieToCart(int, int);
# 
#   void displayCartContents();
# 
#   void printPaymentDetails(string ,string );
# 
#   bool savePaymentDetails(string);
# 
#   ~Customer(){}
# 
# };
# 
# #endif

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Customer.cpp
# #include "Customer.h"
# #include <string>
# #include <iostream>
# #include <iomanip>
# #include <fstream>
# using namespace std;
# 
# Customer::Customer() : cart(&stock), payment(&cart, false, false){};
# 
# void Customer::checkDiscount(bool memberStatus, bool birthdayStatus) {
#   member.setIsMember(memberStatus);
#   member.setIsBirthday(birthdayStatus);
#   payment = Payment(&cart, memberStatus, birthdayStatus);
# }
# 
# void Customer::getMemberDetails(int p, string n, string b, string memberFName) {
#     member.setId(p);
#     member.setName(n);
#     member.setPhoneNum(p);
#     member.setBirthdayDate(b);
#     member.addMember(memberFName);
# }
# 
# bool Customer::loadCookieStockData(string cookieFName) {
#     return stock.loadCookieStockData(cookieFName);
# }
# 
# bool Customer::loadCakeStockData(string cakeFName) {
#     return stock.loadCakeStockData(cakeFName);
# }
# 
# bool Customer::checkMemberFile(string memberFName) {
#   return member.checkMemberFile(memberFName);
# }
# 
#  bool Customer::verifyMember(int memberId, string memberFName) {
#   return member.verifyMember(memberId, memberFName);
#  }
# 
# string Customer::getBirthdayDate() {
#   return member.getBirthdayDate();
# };
# 
# void Customer::displayStockData(string cookieFName, string cakeFName) {
#     stock.displayStockData(cookieFName, cakeFName);
# }
# 
# void Customer::addCakeToCart(int id, int quantity) {
#     cart.addCakeToCart(id, quantity);
# }
# 
# 
# void Customer::addCookieToCart(int id, int quantity) {
#     cart.addCookieToCart(id, quantity);
# }
# 
# void Customer::displayCartContents() {
#     cout << cart;
# }
# 
# void Customer::printPaymentDetails(string cookieFName, string cakeFName) {
#     payment.updateStock(cookieFName,cakeFName);
#     cout << fixed << setprecision(2) << payment;
# }
# 
# bool Customer::savePaymentDetails(string paymentFName) {
#     ofstream outputFile(paymentFName, ios::app);
#     if (outputFile.is_open()) {
#       outputFile << cart;
#       outputFile << "Total price for this order: " << fixed << setprecision(2) << payment.getPriceAfterTax() << endl << endl;
#       outputFile.close();
#       return true;
#     } else {
#         cout << "Unable to save the record." << endl;
#         return false;
#   }
# }
#

"""# Main"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.cpp
# #include "Customer.h"
# #include <string>
# #include <iostream>
# #include <fstream>
# using namespace std;
# const int MAX_ORDERS = 100; // Define a maximum number of orders
# 
# bool validateFilename(const string& filename) {
#     // Check if the filename ends with ".txt"
#     if (filename.length() >= 4 && filename.substr(filename.length() - 4) == ".txt") {
#         return true;
#     } else {
#         return false;
#     }
# }
# 
# bool isBirthday(const string& birthdayDate) {
#     time_t now = time(nullptr);
#     struct tm* timeinfo = localtime(&now);
# 
#     // Extract today's month and day
#     int currentMonth = timeinfo->tm_mon + 1; // tm_mon ranges from 0 to 11
#     int currentDay = timeinfo->tm_mday;
# 
#     // Extract member's birth month and day
#     int birthMonth, birthDay;
#     sscanf(birthdayDate.c_str(), "%*d-%d-%d", &birthMonth, &birthDay);
# 
#     return (currentMonth == birthMonth && currentDay == birthDay);
# }
# 
# bool isValidDate(const string& input) {
#     // Variables to hold year, month, and day parts
#     string yearStr, monthStr, dayStr;
# 
#     // Check different date formats and extract year, month, and day parts
#     if (input.length() == 10 && input[4] == '-' && input[7] == '-') {
#         yearStr = input.substr(0, 4);
#         monthStr = input.substr(5, 2);
#         dayStr = input.substr(8, 2);
#     } else if (input.length() == 9 && input[4] == '-' && input[6] == '-') {
#         yearStr = input.substr(0, 4);
#         monthStr = input.substr(6, 1);
#         dayStr = input.substr(7, 2);
#     } else if (input.length() == 8 && input[4] == '-' && input[6] == '-') {
#         yearStr = input.substr(0, 4);
#         monthStr = input.substr(6, 1);
#         dayStr = input.substr(8, 1);
#     } else if (input.length() == 9 && input[4] == '-' && input[7] == '-') {
#         yearStr = input.substr(0, 4);
#         monthStr = input.substr(5, 2);
#         dayStr = input.substr(8, 2);
#     } else {
#         cout << "Invalid." << endl;
#         return false; // Invalid format
#     }
# 
#     // Validate that yearStr, monthStr, and dayStr contain only numeric digits
#     for (char c : yearStr) {
#         if (!isdigit(c)) {
#             cout << "Please enter integer type value." << endl;
#             return false;
#         }
#     }
#     for (char c : monthStr) {
#         if (!isdigit(c)) {
#             cout << "Please enter integer type value." << endl;
#             return false;
#         }
#     }
#     for (char c : dayStr) {
#         if (!isdigit(c)) {
#           cout << "Please enter integer type value." << endl;
#             return false;
#         }
#     }
# 
#     // Convert the year, month, and day parts to integers
#     int year = stoi(yearStr);
#     int month = stoi(monthStr);
#     int day = stoi(dayStr);
# 
#     // Validate the year, month, and day values
#     if (year < 1900 || year > 2024 || month < 1 || month > 12 || day < 1 || day > 31) {
#         cout << "Out of range"<< endl;
#         return false;
#     }
# 
#     return true;
# }
# 
# istream& readBoolean(istream& is, bool& value) {
#     string input;
#     bool validInput = false;
#     do {
#         cout << "Enter a boolean value (true/false): ";
#         is >> input;
#         if (input == "true" || input == "false") {
#             value = (input == "true");
#             validInput = true;
#         } else {
#             cout << "Invalid input. Please enter 'true' or 'false'." << endl;
#             is.clear(); // Clear failbit
#             is.ignore(); // Clear input buffer until newline
#         }
#     } while (!validInput);
#     return is;
# }
# 
# istream& readPositiveInteger(istream& is, int& value) {
#     bool validInput = false;
#     do {
#         cout << "(Please enter positive integer): ";
#         if (is >> value) {
#             if (value >= 0) {
#                 // Check if only digits were consumed
#                 char c;
#                 if (is.get(c) && (c == '\n' || isspace(c))) {
#                     validInput = true;
#                 } else {
#                     cout << "Invalid input. Please enter a positive integer." << endl;
#                     is.clear(); // Clear failbit to allow further input operations
#                     is.ignore(); // Ignore the rest of the input line
#                 }
#            } else {
#                 cout << "Invalid input. Please enter a positive integer." << endl;
#                 is.clear(); // Clear failbit to allow further input operations
#                 is.ignore(); // Ignore the rest of the input line
#             }
#         } else {
#             cout << "Invalid input. Please enter a positive integer." << endl;
#             is.clear(); // Clear failbit to allow further input operations
#             is.ignore(); // Ignore the rest of the input line
#         }
#     } while (!validInput);
#     return is;
# }
# 
# istream& readValidString(istream& is, string& value) {
#     bool validInput = false;
#     do {
#         cout << "(Please enter a string value): ";
#         is.clear();
#         is.ignore();
#         if (getline(is, value) && !value.empty()) {
#             // Trim leading whitespace
#             while (!value.empty() && (value[0] == ' ' || value[0] == '\t' || value[0] == '\n')) {
#                 value.erase(0, 1);
#             }
# 
#             // Trim trailing whitespace
#             while (!value.empty() && (value.back() == ' ' || value.back() == '\t' || value.back() == '\n')) {
#                 value.pop_back();
#             }
# 
#             if (!value.empty()) {
#                 validInput = true;
#             } else {
#                 cout << "Input cannot be just whitespace. Please enter a non-empty string." << endl;
#             }
#         } else {
#             cout << "Invalid input. Please enter a non-empty string." << endl;
#             is.clear(); // Clear failbit to allow further input operations
#             is.ignore(); // Discard characters until newline
#         }
#     } while (!validInput);
#     return is;
# }
# 
# int main() {
# 
#     Customer customers[MAX_ORDERS]; // Array of Customer objects
#     string cookieFile, cakeFile, memberFile, paymentFile;
# 
#     bool isAdmin=true;
#     bool wannaReenter=true;
#     bool makeOrder = true;
#     cout << "Are admin?" << endl;
#     readBoolean(cin, isAdmin);
# 
#     string defaultPassword = "y1s2bakery!!";
#     string password;
# 
#     if(isAdmin==true)
#     {
#       cout << "Please enter admin password " << endl;
#       readValidString(cin, password);
# 
#       while(password != defaultPassword)
#       {
#         cout << "Wrong password.\nWant to reenter password?" << endl;
#         readBoolean(cin, wannaReenter);
#         if(wannaReenter==true){
#           cout << "Please enter admin password " << endl;
#           readValidString(cin, password);
#         }
#         if(wannaReenter==false)
#         {
#           isAdmin= false;
#         }
#       }
#     }
# 
#     if(isAdmin==false)
#     {
#       cookieFile = "cookiesDetails.txt" ;
#       cakeFile = "cakeDetails.txt" ;
#       memberFile = "memberDetails.txt";
#       paymentFile = "paymentDetails.txt";
#     }
# 
#     if(password == defaultPassword)
#     {
#       cout << "---------------------------------------------------------------------------------------" << endl;
#       cout << "                              FOR INTERNAL USE ONLY                                    " << endl;
#       cout << "---------------------------------------------------------------------------------------" << endl;
#       do {
#           cout << "Please enter the name of cookie file: (example: cookiesDetails.txt)" << endl;
#           cin >> cookieFile;
#           if (!validateFilename(cookieFile)) {
#               cout << "Please make sure it ends with .txt" << endl;
#           }
#       } while (!validateFilename(cookieFile) || !customers[0].loadCookieStockData(cookieFile));
# 
#       do {
#           cout << "Please enter the name of cake file: (example: cakeDetails.txt)" << endl;
#           cin >> cakeFile;
#           if (!validateFilename(cakeFile)) {
#               cout << "Please make sure it ends with .txt" << endl;
#           }
#       } while (!validateFilename(cakeFile) || !customers[0].loadCakeStockData(cakeFile));
# 
#       do {
#           cout << "Please enter the name of member file: (example: memberDetails.txt)" << endl;
#           cin >> memberFile;
#           if (!validateFilename(memberFile)) {
#               cout << "Please make sure it ends with .txt" << endl;
#           }
#       } while (!validateFilename(memberFile) || !customers[0].checkMemberFile(memberFile));
# 
#       do {
#           cout << "Please enter the name of payment file: (example: paymentDetails.txt)" << endl;
#           cin >> paymentFile;
#           if (!validateFilename(paymentFile)) {
#               cout << "Please make sure it ends with .txt" << endl;
#           }
#           if (paymentFile == cookieFile || paymentFile == cakeFile || paymentFile == memberFile)
#           {
#             cout << "Please make sure the file name is not same as previous file name you have entered." << endl;
#           }
# 
#       } while (!validateFilename(paymentFile) || paymentFile == cookieFile || paymentFile == cakeFile || paymentFile == memberFile );
# 
#       cout << "---------------------------------------------------------------------------------------" << endl;
#       cout << endl;
#     }
# 
# 
#     int customerCount = 0; // Track number of customers
# 
#     while ((customerCount < MAX_ORDERS || isAdmin==false) && makeOrder==true) {
#         customers[customerCount].loadCookieStockData(cookieFile);
#         customers[customerCount].loadCakeStockData(cakeFile);
#         bool memberOrNot = true;
#         bool isRetry = false;
#         bool wannaRegister = false;
#         bool isMemberBirthday = false;
#         cout << "Hello! Welcome!" << endl;
#         cout << "Are you a member (true for member, false for non-member)" << endl;
#         readBoolean(cin, memberOrNot);
# 
#         if (memberOrNot == true) {
#             do {
#                 int id;
#                 cout << "Please enter your member ID " << endl;
#                 readPositiveInteger(cin, id);
#                 memberOrNot = customers[customerCount].verifyMember(id, memberFile);
#                 if (!memberOrNot) {
#                     cout << "Do you want to reenter your member ID? " << endl;
#                     readBoolean(cin, isRetry);
#                 }
#             } while (isRetry == true);
#         }
# 
#         if (memberOrNot == false) {
#             memberOrNot = false;
#             cout << "\nDear valued customer, you are not our member yet." << endl;
#             cout << "Do you want to register as a member to enjoy a 10% normal day discount and special 30% birthday discount?" << endl;
#             readBoolean(cin, wannaRegister);
#         }
# 
#         if (memberOrNot == false && wannaRegister == true) {
#             cout << "\nPlease enter your details:" << endl;
# 
#             string name, birthdayDate;
#             int phoneNum;
# 
#             cout << "Name ";
#             readValidString(cin, name);
# 
#             cout << "Phone Number ";
#             readPositiveInteger(cin, phoneNum);
# 
#             do {
#                 cout << "Birthday Date (YYYY-MM-DD) ";
#                 cin >> birthdayDate;
#             } while (!isValidDate(birthdayDate));
# 
#             // Write member details to file
#             customers[customerCount].getMemberDetails(phoneNum, name, birthdayDate, memberFile);
#             memberOrNot = true;
#         }
# 
#         if (memberOrNot) {
#             isMemberBirthday = isBirthday(customers[customerCount].getBirthdayDate());
#             if (isMemberBirthday) {
#                 cout << "\nHappy Birthday! You can now enjoy a 30% birthday discount today!" << endl;
#             }
#         }
# 
#         customers[customerCount].checkDiscount(memberOrNot, isMemberBirthday);
# 
#         if (memberOrNot == false && wannaRegister == false) {
#             cout << "\nNow you will continue as a guest." << endl;
#         }
# 
#         /********************************** Menu **********************************/
#         int inputItemId;
#         int inputItemQuantity;
# 
#         cout << "---------------------------------------------------------------------------------------" << endl;
#         customers[customerCount].displayStockData(cookieFile, cakeFile);
#         cout << "---------------------------------------------------------------------------------------" << endl;
# 
#         /********************************** Cart **********************************/
#         bool wannaPay = false;
#         bool wannaAdd = false;
# 
#         cout << "\nDo you wish to add cookies into your cart?" << endl;
#         readBoolean(cin, wannaAdd);
# 
#         while (wannaAdd == true) {
#             cout << "\nPlease enter the ID of the cookie you wish to add to the cart." << endl;
#             readPositiveInteger(cin, inputItemId);
#             cout << "Please enter the quantity of the cookie you wish to add to the cart." << endl;
#             readPositiveInteger(cin, inputItemQuantity);
# 
#             customers[customerCount].addCookieToCart(inputItemId, inputItemQuantity);
# 
#             cout << "\nAdd again?" << endl;
#             readBoolean(cin, wannaAdd);
#         }
# 
#         cout << "\nNow it's time to add cakes to your cart!" << endl;
#         cout << "Do you wish to add cakes into your cart?" << endl;
#         readBoolean(cin, wannaAdd);
# 
#         while (wannaAdd == true) {
#             cout << "\nPlease enter the ID of the cake you wish to add to the cart." << endl;
#             readPositiveInteger(cin, inputItemId);
#             cout << "Please enter the quantity of the cake you wish to add to the cart." << endl;
#             readPositiveInteger(cin, inputItemQuantity);
# 
#             customers[customerCount].addCakeToCart(inputItemId, inputItemQuantity);
# 
#             cout << "\nAdd again?" << endl;
#             readBoolean(cin, wannaAdd);
#         }
# 
#         cout << "\nThese are the items in your cart." << endl;
#         cout << "---------------------------------------------------------------------------------------" << endl;
#         customers[customerCount].displayCartContents();
#         cout << "---------------------------------------------------------------------------------------" << endl;
# 
#         /********************************** Payment **********************************/
#         cout << "\nContinue with the payment? (true to pay the bill, false to exit)" << endl;
#         readBoolean(cin, wannaPay);
# 
#         if (wannaPay == true) {
#             cout << "---------------------------------------------------------------------------------------" << endl;
#              customers[customerCount].printPaymentDetails(cookieFile, cakeFile);
#              customers[customerCount].savePaymentDetails(paymentFile);
# 
#             cout << "---------------------------------------------------------------------------------------" << endl;
#         }
# 
#         cout << "\nThank you for visiting our shop. See you next time.\n" << endl ;
# 
#         // Increment customerCount for the next customer
#         customerCount++;
# 
#         cout << "Next customer?" << endl;
#         readBoolean(cin, makeOrder);
# 
#         if (customerCount >= MAX_ORDERS) {
#             cout << "Maximum number of orders reached. No more customers can be processed today." << endl;
#         }
#     }
#     return 0;
# }
#

"""# execute main"""

!g++ main.cpp Member.cpp Cart.cpp Customer.cpp Stock.cpp StockItem.cpp Payment.cpp -o output
!./output

192175421